/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTrashRouteImport } from './routes/dashboard/trash'
import { Route as DashboardStarredRouteImport } from './routes/dashboard/starred'
import { Route as DashboardSharedRouteImport } from './routes/dashboard/shared'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrashRoute = DashboardTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStarredRoute = DashboardStarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSharedRoute = DashboardSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/shared': typeof DashboardSharedRoute
  '/dashboard/starred': typeof DashboardStarredRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/shared': typeof DashboardSharedRoute
  '/dashboard/starred': typeof DashboardStarredRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/shared': typeof DashboardSharedRoute
  '/dashboard/starred': typeof DashboardStarredRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/shared'
    | '/dashboard/starred'
    | '/dashboard/trash'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/shared'
    | '/dashboard/starred'
    | '/dashboard/trash'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/shared'
    | '/dashboard/starred'
    | '/dashboard/trash'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trash': {
      id: '/dashboard/trash'
      path: '/trash'
      fullPath: '/dashboard/trash'
      preLoaderRoute: typeof DashboardTrashRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/starred': {
      id: '/dashboard/starred'
      path: '/starred'
      fullPath: '/dashboard/starred'
      preLoaderRoute: typeof DashboardStarredRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shared': {
      id: '/dashboard/shared'
      path: '/shared'
      fullPath: '/dashboard/shared'
      preLoaderRoute: typeof DashboardSharedRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardSharedRoute: typeof DashboardSharedRoute
  DashboardStarredRoute: typeof DashboardStarredRoute
  DashboardTrashRoute: typeof DashboardTrashRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSharedRoute: DashboardSharedRoute,
  DashboardStarredRoute: DashboardStarredRoute,
  DashboardTrashRoute: DashboardTrashRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
